### ISSUE TITLE
Error 404 - Update carriers / update carrier

### ISSUE THREAD

**Issue by MartyQek** [Zasilkovna/WooCommerce#107]
Zdravím,
Po uložení nastavení dopravce, dojde k redirektu: https://example.cz/wp-admin/wp-admin/admin.php?page=packeta-country&code=cz, kde je error 404
Po provedení aktualizace dopravců dojde k redirektu na: https://example.cz/wp-admin/wp-admin/admin.php?page=packeta-country&update_carriers=1 , vyhodí error 404

EN:
Hello,
After saving the settings of carrier, user getting redirected to URL address: https://example.cz/wp-admin/wp-admin/admin.php?page=packeta-country&code=cz , where is an 404 error
After saving the update of carriers, user getting redirected to URL address: https://example.cz/wp-admin/wp-admin/admin.php?page=packeta-country&update_carriers=1 where is an 404 error

**Comment by packeta** [comment]
Dobrý den, 
na odstranění problému pracujeme.  Novou verzi vydáme co nejdříve.

**Comment by packeta** [comment]
Dobrý den, 
problém byl opraven ve verzi 1.0.2 - ke stažení zde: https://github.com/Zasilkovna/WooCommerce/releases/download/v1.0.2/woocommerce-modul-packeta-1.0.2.zip
