### ISSUE TITLE
Verze 1.0.3 pokladna

### ISSUE THREAD

**Issue by webprojekty** [Zasilkovna/WooCommerce#119]
Poslední krok platby - pokladna, nad výběrem pickup pointu se tvoří prázdné řádky a formulář nahoře je rozhozený
![Screenshot 2021-12-11 171009](https://user-images.githubusercontent.com/47626020/145683735-b6c319f6-4332-4f47-ac10-44883d5e9a84.png)

**Comment by packeta** [comment]
Dobrý den, pracujeme na opravě tohoto problému.  Bude opraveno ve verzi 1.0.4

**Comment by packeta** [comment]
Vydali jsme novou verzi 1.0.4,  která řeší tento problém. Instalaci pluginu můžete stáhnout zde: https://github.com/Zasilkovna/WooCommerce/releases/download/v1.0.4/woocommerce-modul-packeta-1.0.4.zip

**Comment by webprojekty** [comment]
poslal jsem Vám na mail chybu co způsobuje nyní aktivace verze 1.0.4
