### ISSUE TITLE
Spolupráce

### ISSUE THREAD

**Issue by vaclavgreif** [Zasilkovna/WooCommerce#133]
Ahoj, jsem spolu s Danem Mejtou autorem pluginu [Wpify Woo](https://wordpress.org/plugins/wpify-woo/), který kromě jiného umožňuje integraci na Zásilkovnu. Narazil jsem teď na tento plugin, vypadá to výborně..:-) 

Rádi bychom nabídli možnou spolupráci při vývoji vašeho pluginu - pomoc s nasazením na wp.org, přidání podpory PHP8 ad. - nedává smysl udržovat verzi v našem pluginu, když bude existovat plugin na oficiální integraci.

Co si o tom myslíte?..:-)

**Comment by packeta** [comment]
Dobrý den,   spolupráci se určitě nebráníme.  Napište mi prosím na technicka.podpora@zasilkovna.cz kontakt přímo na Vás a co nejdříve se spolu spojíme a probereme možnosti.

S pozdravem Jaroslav Malý
