### ISSUE TITLE
FR: Allow configuration import/export

### ISSUE THREAD

**Issue by fourstepper** [Zasilkovna/WooCommerce#145]
Right now, the configuration can be exported for debug purposes, however I think it would also be great if the configuration could be imported as well

**Comment by MatyasKoval** [comment]
Hello,
 Currently we are not considering adding this function, but thank you for the suggestion nonetheless. If you wish, you can make a pull request.

**Comment by MatyasKoval** [comment]
> Right now, the configuration can be exported for debug purposes, however I think it would also be great if the configuration could be imported as well

Hello,
Currently we are not considering adding this function, but thank you for the suggestion nonetheless. If you wish, you can make a pull request.
