### ISSUE TITLE
Issues with packeta filtering

### ISSUE THREAD

**Issue by uhlhosting** [Zasilkovna/WooCommerce#169]
Hi,

The filters should work only on order pages:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/6324047/160723459-3d5e9aea-3f76-4867-8974-cdf08d83577a.png">

nor on the posts:
<img width="999" alt="image" src="https://user-images.githubusercontent.com/6324047/160723685-a2ac157d-4d95-4959-838a-77a58e693cfa.png">

Also consider to add the option to resend to Packeta/Zasilkovna orders that were made and for some reason failed at first.

**Comment by MatyasKoval** [comment]
Hello @uhlhosting ,
thank you for the reported issue. This should not happen and we will definitely work on fixing it in the future version of our plugin.

As for your question, orders that fail to be submitted have a reason (usually incorrect data of the order) why they failed and therefore require manual editing before being submitted again. In the future, we plan on adding an option to cancel a packet from the administration which will allow to submit said packet again.

Best regards,
Matyáš Kovaľ - Packeta Technical Support

**Comment by uhlhosting** [comment]
We had for example issues with plugins who did not had an option to add default values for shipping weight. Therefor such packages should be allowed to add weight and resend to packeta. 

Thanks for your reply, also in my opinion since we deal with a woocommerce plugin, would be much easier if the plugin is added im the woocommerce menu. To avoid increasing main menu in wordpress admin menu, since if any woocommerce modul will be in main menu, well could be in the end quite a lot. 

Otherwise great job, and really appreciated, since modules we had until now were like bad joke and only tried to make big money of something that should be simple and free for users.
