### ISSUE TITLE
Access API from another plugin

### ISSUE THREAD

**Issue by gamelaster** [Zasilkovna/WooCommerce#191]
I need to implement getting the information about pickup point (by WC Order ID) from another plugin, although, unless using nasty hacks, I can't find any other way of doing this. Is there any official way of getting this information from paketa plugin?

Thanks

**Comment by gamelaster** [comment]
Hi @MatyasKoval ,

Thank you for the fast reply. The plugin is some really poorly designed email designer (probably paid?), I just got task to implement a function inside to this plugin to print the address to packeta store into email.

And okay, I meant "nasty hack" by exactly doing this, getting the data from database, but I hoped that there is some official way.

Thanks 😊

**Comment by MatyasKoval** [comment]
Hello @gamelaster,
sorry for the inconvenience caused. 

In the 1.2 version of our plugin, we moved the metadata from the posts table to our own custom table, so that is probably why your method stopped working.

As stated before there is no other "official" way to access this data other than accessing the DB table directly. 

Best regards,
Matyáš Kovaľ - IT support Packeta

**Comment by gamelaster** [comment]
Hi @MatyasKoval ,

thanks for the information! I just made it by reading the data directly from the database, and it works great, I think this solution is just fine, unless this will be changed in future.

Thanks.

**Comment by MatyasKoval** [comment]
Hello @gamelaster,
I am glad to hear you were successfull in your implementation. 

Just please be aware, that as mentioned in the previous response (https://github.com/Zasilkovna/WooCommerce/issues/191#issuecomment-1096751312) our database structure can and sometime in the future probably will change (same as with the metadata removal).

We will try to think up an official solution for getting various plugin data in ways other than directly accessing the database tables in the future, but as of now we can not really promise when or even if we will come up with a solution.

Best regards,
Matyáš Kovaľ - IT support Packeta
