### ISSUE TITLE
Issue on UI side

### ISSUE THREAD

**Issue by uhlhosting** [Zasilkovna/WooCommerce#196]
![image](https://user-images.githubusercontent.com/6324047/163017594-ca38fdd2-dd96-493c-900b-78208e56ad9c.png)
On the Czech version there are a bit too wide buttons that go out of the viewport of WooCommerce, maybe lower the amount of text in that button, or make it in two lines.

**Comment by MatyasKoval** [comment]
Hello @uhlhosting ,
Thank you for the reported issue, but sadly I was unable to replicate this. 

When I tried it on any of my devices and browsers, the admin menu was responsive and changed it's button sizes etc. in accordance to the resolution of the window. 

Can you please tell me which internet browser you are using, it's version and the resolution of your device?
Are you using any plugins that could modify the admin layout of the order?
Thank you.

Best regards,
Matyáš Kovaľ - IT Support Packeta

**Comment by uhlhosting** [comment]
I tried in every browser. Safari, chrome and firefox. They are all the same.
