### ISSUE TITLE
CRITICAL: Packeta preventing checkout

### ISSUE THREAD

**Issue by fourstepper** [Zasilkovna/WooCommerce#244]
<span class="message-body-wrapper">

x-qm-php_errors-error-1 | {"key":"815b057c28bf7be94415b485e780253e","type":"notice","message":"Undefined  index:  _wpnonce","file":"wp-content\/plugins\/packeta\/src\/Packetery\/Module\/Checkout.php","line":353,"stack":["Packetery\\M\\Checkout->validateCheckoutData()","do_action('woocommerce_checkout_process')","WC_Checkout->process_checkout()","WC_AJAX::checkout()","do_action('wc_ajax_checkout')","WC_AJAX::do_wc_ajax()","do_action('template_redirect')"],"component":"Plugin:  packeta"}
-- | --
</span>

When using packeta and not using it to ship to a specific country, I get 403 Forbidden from the `?wc-ajax=checkout` endpoint. When I remove the packeta plugin, everything continues to work as expected.

**Comment by fourstepper** [comment]
Downgrading to v1.2.6 helped. If you need other help debugging this, I am tentatively available.

Best,
Robin

**Comment by MatyasKoval** [comment]
Hello @fourstepper, 
Thank you for the report! 

We were able to replicate this issue and started working on a fix. The fix will be a part of the next update, that will come out as soon as we find a solution.

Best regards,
Matyáš Kovaľ - E-Commerce Support

**Comment by MatyasKoval** [comment]
@fourstepper  Hello,
in the meantime, we have found a solution and fixed this behaviour in the newest version of the plugin- 1.3.2 
Are you experiencing this issue with this version of the plugin or has this fixed it on your end as well?

Best regards,
Matyáš Kovaľ - E-Commerce Support

**Comment by fourstepper** [comment]
@MatyasKoval thanks for the quick reaction. I have enabled 1.3.2 but some issues returned. Downgraded, can't yet confirm this is 100% caused by Packeta though

**Comment by MatyasKoval** [comment]
@fourstepper Hello,
just checking to make sure, is this particular issue resolved on your side as well then?

Best regards,
Matyáš Kovaľ - E-Commerce Support

**Comment by fourstepper** [comment]
Hi @MatyasKoval , I can confirm this issue is no longer present.

Thank you for the quick fix and best regards,
Robin
