### ISSUE TITLE
Produkty bez hmotnosti = 0kg dopočítanie hmotnosti balenia.

### ISSUE THREAD

**Issue by Rik-TRIFY** [Zasilkovna/WooCommerce#251]
Chcel by som sa spýtať, či je možné urobiť zmenu v tom, aby ked si v nastaveniach pluginu packeta zadám hmotnosť balenia 3kg aby táto hmotnosť bola braná ako hmotnosť balíčka.

Naše produkty neobsahujú hmotnosť na karte. Všetky produkty sú do hmotnosti cca 500g ale upraviť v eshope stovky kariet je pre nás zbytočné. Keby bola možnosť aby sa hmotnosť balenia rátala ako celková hmotnosť bolo by to fajn. Plugin ktorý sme predtým používali (no skončila už podpora) mal v sebe nastavenie, že ak nebola na karte uvedená hmotnosť produktu tak zarátalo za produkt (položku) nastavenú hodnotu (v našom prípade 500g). ak boly v objednávke 3 položky vypočítalo hmotnosť balíka 1,5kg a slo odoslať hromadne. 

Teraz to tak nieje a pri každej objednávke musíme dopispovať hmotnosť čo je zbytočne zdĺhavé. Mysleli sme si že to hmotnosť balenia dopočíta sama, no nerobí to.

**Comment by MatyasKoval** [comment]
Dobrý den @Rik-TRIFY ,
nastavení hmotnosti obalového materiálu funguje tak, že se jedná o hmotnost, která se k objednávce připočte, pokud má objednávka hmotnost větší než 0 (spočteno z hmotnosti jednotlivých produktů v objednávce). 
Takto implementovaná je z důvodu, že Zásilkovna vyžaduje udání hmotnosti zásilky při jejím podání do systému. Povinnost uvádět hmotnost zásilky byla přidána, aby Zásilkovna mohla lépe odhadovat zatížení přepravních vozidel a zlepšit tím své služby díky lepšímu odhadu a zrychlení přepravy. 
To ale vyžaduje, aby hmotnost zásilky v datech skutečně odpovídala hmotnosti zásilky a proto takovéto automatické doplnění hmotnosti není implementováno a ani do budoucna se neplánuje takovouto funkcionalitu implementovat.

S přáním krásného dne,
Matyáš Kovaľ - E-Commerce support

**Comment by Rik-TRIFY** [comment]
Zdravím @MatyasKoval , Ja to velmi dobre chápem ako to u zásielkovne funguje. Je mi jasné že musia vedieť hmotnosť zasielky aby sa im s nou lepsie pracovalo, doručovalo...

Preto som sa pýtal či tam nieje možnosť niekde nastaviť ze ak produkt nemá nastavenú hmotnost tak to v objednávke prída 500g (čo je realne cca hmotnosť našich produktov).

Predchádzajúci plugin ktorý sme používali, ten v sebe túto funkciu mal a fungovalo to, a nebol s tým nikde problém, ani u zasielkovne, proste nikde. 
Skúste to doplniť ako rozšírenie pre eshopy ktoré nemajú váhu produktov.
Niekoľko eshopov do ktorých mám prístup tak nemajú uvádzanú hmotnosť a to preto, že položky produktov stahujú cez feed a ten neobsahuje hmotnost. a upravovať ručne 10k položiek... ehm...

**Comment by MatyasKoval** [comment]
Dobrý den @Rik-TRIFY,
omlouvám se za opožděnou odpověď.

V další verzi našeho pluginu (1.3.3) přibude filtr, kterým bude celkově možné upravovat údaje o zásilce před jejím odesláním do našeho systému. 

Jak tento filtr využijete bude již přímo na Vás - měl by jít upravit i tak, jak popisujete Vy. Jen v rámci Zásilkovny jako takové, vzhledem k tomu, že váha je povinným parametrem, je žádoucí aby skutečná váha zásilky co nejvíce odpovídala skutečnosti, viz informace, které jsem psal v předchozí odpovědi.

S přáním krásného dne,
Matyáš Kovaľ – Packeta E-Commerce Support

**Comment by MatyasKoval** [comment]
Dobrý den, 
omlouvám se za opožděné aktualizace k tomuto tématu.

Výše zmiňovaný filtr je již delší dobu (od verze 1.4) dostupný a bližší informace k němu jsou součástí README souboru pluginu.

Vámi zmiňovaná funkcionalita defaultování na určitou váhu může být v základu přidána například takto:

add_filter( 'packeta_create_packet', function ( array $createPacketData ): array {
	$createPacketData['weight'] = 1.5;
	return $createPacketData;
} );

Pokud by s touto funkcionalitou byly jakékoliv potíže z Vaší strany, prosím, dejte nám vědět na technicka.podpora@zasilkovna.cz

S pozdravem,
Matyáš Kovaľ - Packeta E-Commerce Support
