### ISSUE TITLE
Problém s pluginem: Back In Stock Notifier

### ISSUE THREAD

**Issue by pBrambi** [Zasilkovna/WooCommerce#253]
Zdravím,

objevuje se závažný bug na webech (3 weby celkem, všude stejné). Provedl jsem klasickou "diagnózu" a postupně vypínal všechny pluginy a nastavil výchozí šablonu a zjistil, že Váš plugin si nerozumí s pluginem **"Back In Stock Notifier"** (https://wordpress.org/plugins/back-in-stock-notifier-for-woocommerce/), který na všech 3 webech právě využívám.

Chyba nastává **pouze při odesílání e-mailu / upozornění** z výše zmíněného pluginu a to konkrétně tato níže:

**Verze pluginů Zasílkovna / Back In Stock Notifier:** nejnovější verze dne 19. 6. 2022
**Verze WP: 6.0**
**Verze WooCommerce:**  6.6.0
**Modifikace šablon e-mailů WooCommerce:** žádná, defaultní WooCommerce e-maily, pouze upraven text / předmět v WooCommerce > Nastavení > Emaily přes běžné nastavení
**Testováno na mailerech:** interní "Wordpressový" php mail, SMTP server

`Na řádku č. 532 v souboru /data/www/24863/posse_cz/www/wp-content/plugins/packeta/src/Packetery/Module/Plugin.php došlo k chybě typu E_ERROR. Chybová zpráva: Uncaught TypeError: Packetery\Module\Plugin::render_email_footer(): Argument #1 ($email) must be of type ?WC_Email, string given, called in /data/www/24863/posse_cz/www/wp-includes/class-wp-hook.php on line 307 and defined in /data/www/24863/posse_cz/www/wp-content/plugins/packeta/src/Packetery/Module/Plugin.php:532
Stack trace:
#0 /data/www/24863/posse_cz/www/wp-includes/class-wp-hook.php(307): Packetery\Module\Plugin->render_email_footer('Automaticky gen...')
#1 /data/www/24863/posse_cz/www/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#2 /data/www/24863/posse_cz/www/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#3 /data/www/24863/posse_cz/www/wp-content/plugins/back-in-stock-notifier-for-woocommerce/includes/abstract-mailer.php(64): do_action('woocommerce_ema...', 'Automaticky gen...')
#4 /data/www/24863/posse_cz/www/wp-content/plugins/back-in-stock-notifier-for-woocommerce/includes/abstract-mailer.php(83): CWG_Instock_Mailer->format_html_message()
#5 /data/www/24863/posse_cz/www/wp-content/plugins/back-in-stock-notifier-for-woocommerce/includes/admin/class-post-type.php(336): CWG_Instock_Mailer->send()
#6 /data/www/24863/posse_cz/www/wp-includes/class-wp-hook.php(307): CWG_Instock_Post_Type->send_manual_mail('')
#7 /data/www/24863/posse_cz/www/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#8 /data/www/24863/posse_cz/www/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#9 /data/www/24863/posse_cz/www/wp-admin/admin.php(419): do_action('admin_action_cw...')
#10 /data/www/24863/posse_cz/www/wp-admin/edit.php(10): require_once('/data/www/24863...')
#11 {main}
thrown`

**Comment by MatyasKoval** [comment]
Dobrý den @pBrambi,
děkujeme moc za nahlášení tohoto chování. 
Pro plugin Back in Stock Notifier, jakožto externí plugin, jsme podporu v základu neimplementovali.
Vámi nahlášené chování se mi podařilo replikovat i na naší straně a předal jsem ho k prověření kolegům programátorům, zda by nebylo možné plugin upravit, aby tuto chybu nevyvolával.

S přáním krásného dne,
Matyáš Kovaľ - E-Commerce Support

**Comment by pBrambi** [comment]
Zdravím, není zač a bohužel pro Vás nemám lepší zprávu, ale problém není pouze s tímto pluginem, ale i s **dalším** _(zatím jsem nezjistil další jiné)_ a to myslím komunikuje přes WP API převážně a modul je jen "spojení".

Jedná se o systém ManageWP (https://wordpress.org/plugins/worker/), který už je ale daleko rozšířenějším, než plugin z problému předešlého. Chyba sice nehází fatalní chybu na webu a web dále funguje,  ale web "odpojí" ze systému s hláškou:

`Invalid value in $_POST/$_COOKIE in key 'redirect_count', expected string, integer given. occurred in wp-content/plugins/packeta/packetery_vendor/nette/http/src/Http/RequestFactory.php on line 170 please make sure that [your website](https://dharmagaia.cz/) is accessible`

Bohužel více informací nevidím, protože v debug.log se neukládají, ale snad pomůže i toto.

**Verze pluginů Zasílkovna / ManageWP**: nejnovější verze ke dni 20. 6. 2022
**Verze WP:** 6.0
**Verze WooCommerce:** 6.6.0

**Informace o serveru**: 


```
### wp-core ###

version: 6.0
site_language: cs_CZ
user_language: cs_CZ
timezone: Europe/Prague
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 92
dotorg_communication: true

### wp-mu-plugins (1) ###

ManageWP - Worker Loader: version: 1.0.0, author: GoDaddy

### wp-server ###

server_architecture: FreeBSD 13.1-STABLE amd64
httpd_software: Apache
php_version: 8.0.19 64bit
php_sapi: fpm-fcgi
max_input_variables: 5000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 1024M
php_post_max_size: 1024M
curl_version: 7.83.1 OpenSSL/1.1.1n
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.4.24-MariaDB-log
client_version: mysqlnd 8.0.19
max_allowed_packet: 33554432
max_connections: 312

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /data/www/24863/dharmagaia_cz/www/wp-content
WP_PLUGIN_DIR: /data/www/24863/dharmagaia_cz/www/wp-content/plugins
WP_MEMORY_LIMIT: 64M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: true
COMPRESS_SCRIPTS: true
COMPRESS_CSS: true
WP_ENVIRONMENT_TYPE: Nedefinováno
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable


```

**Comment by MatyasKoval** [comment]
Dobrý den, 
omlouvám se za opožděné aktualizace k tomuto tématu.

Od verze 1.4 našeho pluginu dál plugin podporuje propojení s Manage WP a od verze 1.3.3 plugin Back in Stock Notifier a pluginy využívající podobné funkcionality, které způsobovaly výše zmíněné chyby. 

Pokud by s těmito funkcionalitami byly jakékoliv potíže z Vaší strany, prosím, dejte nám vědět na technicka.podpora@zasilkovna.cz

S pozdravem,
Matyáš Kovaľ - Packeta E-Commerce Support
