### ISSUE TITLE
Seznam výdejních míst není k dispozici (PL)

### ISSUE THREAD

**Issue by MarelisAdlatus** [Zasilkovna/WooCommerce#506]
Pro zemi Polsko je seznam výdejních míst prázdný, další země ukazují v pořádku (CZ, SK).
> Obchod je ve stavu testování ...

```
checkout.js?ver=78e8d6917e154cba97890a98e9525da2:534 Pickup point widget options: apiKey: 4509518a3bcd918b, country: pl, language: cs, appIdentity: 
WordPress-6.4.3-Woocommerce-8.6.1-Packeta-1.7.1, weight: 0.2, carriers: 3060
library.js?_=1709982435443:265 Widget health check result: true
library.js?_=1709982435443:268 starting Widget
v6/:1 Wiget initialization
main.ec667fda.chunk.js:2 insertGoogleAnalytics {inserted: undefined}inserted: undefined[[Prototype]]: Object
2.d686d6ef.chunk.js:2 v6 widget health check result: true
2.d686d6ef.chunk.js:2 v6 widget enable geoapify check result: true
```

![7a40247c-d9df-4843-86a1-64ebc8c0f28e](https://github.com/Zasilkovna/WooCommerce/assets/119352137/621b75f0-4799-4974-9054-f37809c0784c)

[packeta_options_export_2024-03-09-11-09-53.txt](https://github.com/Zasilkovna/WooCommerce/files/14546046/packeta_options_export_2024-03-09-11-09-53.txt)

**Comment by MatyasKoval** [comment]
Dobrý den @MarelisAdlatus,
toto chování nesouvisí přímo s pluginem a jeho nastavením, ale s nastavením klientského účtu v Zásilkovně.

V Polsku nemáme přímo svoje výdejní místa, ale pouze místa dopravců, se kterými spolupracujeme, která defaultně nejsou zobrazována. Je třeba je specificky povolit v klientské sekci účtu, který používáte [zde](https://client.packeta.com/cs/user-branch-settings/edit). 

Jde konkrétně o nastavení "Zobrazení externích výdejních míst" které je třeba povolit. Tato změna nastavení může chvíli trvat než se propíše, tedy do řádově hodin od přenastavení by se vám již měla výdejní místa v Polsku začít zobrazovat.

S pozdravem,
Matyáš Kovaľ - Packeta E-Commerce Support

**Comment by MarelisAdlatus** [comment]
Dobrý den @MatyasKoval ,
nastaveno a funguje to ! 😄 
Děkuji,
ML
