### ISSUE TITLE
Neukazuje se mi tlačitko zasilkovná, všechno správně nastaveno

### ISSUE THREAD

**Issue by matysek66055** [Zasilkovna/WooCommerce#530]
Zdravím, mám menší problém neukazuje se mi nikde tlačitko v checkoutu, co mám dělat ?

**Comment by matysek66055** [comment]
![image](https://github.com/Zasilkovna/WooCommerce/assets/83514184/7d0805dc-b448-4d63-a107-a6e0c7e303cc)
Vidim pouze toto, nemohu nikde nastavit adresu pouze :
![image](https://github.com/Zasilkovna/WooCommerce/assets/83514184/e0d81e10-13e0-4fff-b0b6-a814d9387072)

**Comment by paperbonsai** [comment]
Jak jsi to vyřešil?
