### ISSUE TITLE
Fatal error při aktivaci /  Fatal error when I activate the plugin

### ISSUE THREAD

**Issue by MartyQek** [Zasilkovna/WooCommerce#96]
Po aktivaci pluginu, plugin není aktivován a vyhodí tento error / After I activating the plugin, the plugin didn't get activated and throws this error:

Fatal error: Uncaught PacketeryNette\DI\ServiceCreationException: Service (PacketeryGuzzleHttp\Client::__construct()): Class PacketeryGuzzleHttp\Client not found. in /data/web/virtuals/265190/virtual/www/domains/milanoshop.cz/wp-content/plugins/packetery/packetery_vendor/nette/di/src/DI/Resolver.php:139 Stack trace: #0 /data/web/virtuals/265190/virtual/www/domains/milanoshop.cz/wp-content/plugins/packetery/packetery_vendor/nette/di/src/DI/Definitions/ServiceDefinition.php(184): PacketeryNette\DI\Resolver->resolveEntityType(Object(PacketeryNette\DI\Definitions\Statement)) #1 /data/web/virtuals/265190/virtual/www/domains/milanoshop.cz/wp-content/plugins/packetery/packetery_vendor/nette/di/src/DI/Resolver.php(70): PacketeryNette\DI\Definitions\ServiceDefinition->resolveType(Object(PacketeryNette\DI\Resolver)) #2 /data/web/virtuals/265190/virtual/www/domains/milanoshop.cz/wp-content/plugins/packetery/packetery_vendor/nette/di/src/DI/ContainerBuilder.php(294): PacketeryNette\DI\Resolver->resolveDefinition(Object(PacketeryNette in /data/web/virtuals/265190/virtual/www/domains/milanoshop.cz/wp-content/plugins/packetery/packetery_vendor/nette/di/src/DI/Resolver.php on line 139

**Comment by MartyQek** [comment]
Issue was successfully resolved.

**Comment by packeta** [comment]
Problém by měl být vyřešen ve verzi 1.0.1.  Prosím, vyzkoušejte.

**Comment by lukasprelovsky** [comment]
Problem nastava aj vo verzii v1.0.6
